### ISSUE TITLE
Meta Og 기본값 기능 버그 해결

### ISSUE THREAD

**Issue by GC-Park** [woowacourse/prolog#1495]
# 구현할 기능

- [x] 아티클 Meta Og 기본값 삽입 기능 버그 해결하기
- [x] 아티클 링크 입력 전에 타이틀, 썸네일 폼 안 보이도록 수정
- [x] input에서 enter키 눌렀을 때 새로고침 안되도록 수정

빠르게 수정 후 dev 서버에 배포해 확인하고 main으로 merge 하도록 한다.
