### ISSUE TITLE
useMutation 커스텀 훅을 React Query로 마이그레이션한다

### ISSUE THREAD

**Issue by wonsss** [woowacourse/prolog#948]
광범위한 코드에 영향을 미치며 사용상 실수 가능성이 큰 useMutation 커스텀 훅부터 우선적으로 변경

## Tasks

- [x] components/Introduction.js
- [x] components/ProfilePageSideBar.js
- [x] components/ProfilePageScraps.js
