### ISSUE TITLE
useMutation 커스텀 훅을 React Query로 마이그레이션한다 (2)

### ISSUE THREAD

**Issue by euijinkk** [woowacourse/prolog#959]
광범위한 코드에 영향을 미치며 사용상 실수 가능성이 큰 useMutation 커스텀 훅부터 우선적으로 변경

## Tasks

- [ ] pagse/StudylogPage/index.js
- [ ] hooks/useStudyLog.js
- [ ] contexts/UserProvider.js
